ejobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = 'error_handling.views.custom_404'
handler500 = 'error_handling.views.custom_500'


urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path('index/<int:pk>/', views.job_type_detail, name='vacs'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path("bio_info/", views.bio_info, name="bio_info"),
    path('basic_info/<int:user_id>/', views.basic_info, name='basic_info'),
    path('basic_academic/', views.basic_academic, name='basic_academic'),
    path('high_school/', views.high_school, name='high_school'),
    path('college/', views.college, name='college'),
    path('update_basic_education/<int:instance_id>/',
         views.update_basic_academic, name='update_basic_education'),
    path('delete_basic_education/<int:instance_id>/',
         views.delete_basic_academic, name='delete_basic_education'),
    path('further_studies/', views.further_studies, name='further_studies'),
    path('update_further_studies/<int:instance_id>/',
         views.update_further_studies, name='update_further_studies'),
    path('delete_further_studies/<int:instance_id>/',
         views.delete_further_studies, name='delete_further_studies'),
    path('certs/', views.certs, name='certs'),
    path('certification/', views.certification, name='certification'),
    path('update_certification/<int:instance_id>/',
         views.update_certification, name='update_certification'),
    path('delete_certification/<int:instance_id>/',
         views.delete_certification, name='delete_certification'),
    path('memberships/', views.memberships, name='memberships'),
    path('membership/', views.membership, name='membership'),
    path('update_membership/<int:instance_id>/',
         views.update_membership, name='update_membership'),
    path('delete_membership/<int:instance_id>/',
         views.delete_membership, name='delete_membership'),
    path('experience/', views.experience, name='experience'),
    path('work_experience/', views.work_experience, name='work_experience'),
    path('update_work_experience/<int:instance_id>/',
         views.update_work_experience, name='update_work_experience'),
    path('delete_work_experience/<int:instance_id>/',
         views.delete_work_experience, name='delete_work_experience'),
    path('referees/', views.referees, name='referees'),
    path('refs/', views.refs, name='refs'),
    path('update_referees/<int:instance_id>/',
         views.update_referee, name='update_referee'),
    path('delete_referee/<int:instance_id>/',
         views.delete_referee, name='delete_referee'),
    path('career_objective/', views.career_objective, name='career_objective'),
    path('update_career_objective/', views.update_career_objective,
         name='update_career_objective'),
      path('resume/', views.resume, name='resume'),
    path('terms/', views.terms, name='terms'),
    path('staff/', views.staff, name='staff_profile'),
    path('update_educational_level/',
         views.update_educational_level, name='edu_level'),
    path('how_to_apply/', views.how, name='how'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path('login/', views.custom_login, name='login'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('secure/<uidb64>/<token>', views.secure, name='secure'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path('create_staff/', views.create_access_level_5_user, name='create_staff'),
    path("staff_no/", views.staff_no, name="staff_no"),
    path("permission_denied/", views.not_allowed, name="denials"),
    path("f_pass", views.f_pass, name="f_pass"),
    path('del_user/<int:user_id>', views.delete_user, name='del_user'),
    path('terms_acceptance/',
         views.terms_acceptance, name='terms_acceptance'),
    path('vacancy/<int:vacancy_id>/terms_acceptance/',
         views.internal_terms_acceptance, name='internal_terms_acceptance'),
    path('internship/<int:vacancy_id>/terms_acceptance/',
         views.internship_terms_acceptance, name='internship_terms_acceptance'),
    path('attachment/<int:vacancy_id>/terms_acceptance/',
         views.attachment_terms_acceptance, name='attachment_terms_acceptance'),
]

vacancies/urls.py
from django.urls import path
from . import views

app_name = 'vacancies'
urlpatterns = [
    path('job/<int:vacancy_id>/', views.job, name='job'),
    path("internships", views.internships, name="internships"),
    path('internship/<int:vacancy_id>/', views.internship, name='internship'),
    path("attachments", views.attachments, name="attachments"),
    path('attachment/<int:vacancy_id>/', views.attachment, name='attachment'),
    path('apply/<int:vacancy_id>/', views.apply, name='apply'),
    path('applications/', views.applications, name='applications'),
    path('reapply/<int:application_id>/',
         views.reapply_application, name='recall_application'),
    path('delete/<int:application_id>/',
         views.delete_application, name='delete_application'),
    path("internal", views.internal, name="internal"),
    path('internal_detail/<int:vacancy_id>/',
         views.internal_detail, name='internal_detail'),
    path('application/success/', views.application_succ, name='apply_succ'),
    path('vacancies/apply_fail', views.apply_fail, name='apply_fail'),

]

vacancies/views.py
from django.core.exceptions import ValidationError
from .models import Application, Resume, WorkExperience, Certification
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .models import *
from django.db.models import Q
from users.models import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import user_passes_test
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.utils.html import format_html
from .work_experience import calculate_work_experience
from .checks import *
from django.utils import timezone
from .check_qualifications import *
from .create_application import *
from .send_mail import *
import uuid
from .ref_number import *
import datetime
from django.utils import timezone
from users.decorators import *
from .applicant_experience import *
from main.mails import *


def user_has_access_level_5(user):
    return user.is_authenticated and user.access_level == 5


@login_required
def job(request, vacancy_id):
    job = get_object_or_404(Vacancy, id=vacancy_id,
                            vacancy_type='employment', published=True)

    # Get the UserAcceptedTerms instance for the logged-in user
    user_accepted_terms, created = UserAcceptedTerms.objects.get_or_create(
        user=request.user
    )

    context = {
        'vacancy': job,
        'user_accepted_terms': user_accepted_terms,
    }

    return render(request, 'vacancies/job.html', context)


def internships(request):
    search_query = request.GET.get('search')
    vacancy_type_filter = request.GET.get('vacancy_type')
    current_date = date.today()  # Get the current date

    internships = Vacancy.objects.filter(
        vacancy_type='internship',
        published=True,
        date_open__lte=current_date,  # Filter for open internships based on date
        date_close__gte=current_date,  # Filter for open internships based on date
    )

    if search_query:
        internships = internships.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query)
        )

    if vacancy_type_filter:
        internships = internships.filter(vacancy_type=vacancy_type_filter)

    job_disciplines = JobDiscipline.objects.all()

    context = {
        'internships': internships,
        'selected_vacancy_type': vacancy_type_filter,
        'search_query': search_query,
        'job_disciplines': job_disciplines,
    }
    return render(request, 'vacancies/internships.html', context)


@login_required
def internship(request, vacancy_id):
    internship = get_object_or_404(
        Vacancy, id=vacancy_id, vacancy_type='internship', published=True)

    user_accepted_terms, created = UserAcceptedTerms.objects.get_or_create(
        user=request.user
    )
    return render(request, 'vacancies/internship.html', {'vacancy': internship, 'user_accepted_terms': user_accepted_terms})


def attachments(request):
    search_query = request.GET.get('search')
    vacancy_type_filter = request.GET.get('vacancy_type')
    current_date = date.today()  # Get the current date

    attachments = Vacancy.objects.filter(
        vacancy_type='attachment',
        published=True,
        date_open__lte=current_date,
        date_close__gte=current_date,
    )

    if search_query:
        attachments = attachments.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query)
        )

    if vacancy_type_filter:
        attachments = attachments.filter(vacancy_type=vacancy_type_filter)

    job_disciplines = JobDiscipline.objects.all()

    context = {
        'attachments': attachments,
        'selected_vacancy_type': vacancy_type_filter,
        'search_query': search_query,
        'job_disciplines': job_disciplines,
    }
    return render(request, 'vacancies/attachments.html', context)


@login_required
def attachment(request, vacancy_id):
    attachment = get_object_or_404(
        Vacancy, id=vacancy_id, vacancy_type='attachment', published=True)

    user_accepted_terms, created = UserAcceptedTerms.objects.get_or_create(
        user=request.user
    )

    context = {
        'vacancy': attachment,
        'user_accepted_terms': user_accepted_terms,
    }
    return render(request, 'vacancies/attachment.html', context)


def send_application_confirmation_email(user, vacancy, reference_number):
    """
    This function sends an application confirmation email to the user.
    """

    # Construct the email subject
    mail_subject = f"Application successful for {vacancy.title}"

    full_name = user.username
    vacancy_details = f"{vacancy.title} ({vacancy.ref})"

    # Construct the email message
    user_message = (
        f"Dear {full_name},\n\n"
        f"Your application for {vacancy_details} has been successfully made. "
        f"Only shortlisted candidates will be contacted.\n\n"
        f"Your application reference number is: {reference_number}\n\n"
        f"Regards,\nKenGen Careers Portal"
    )

    # Use the custom email function to send the email
    send_custom_email(
        subject=mail_subject,
        message=user_message,
        send_to=[user.email]
    )


@login_required
def apply(request, vacancy_id):
    def redirect_with_error(message):
        messages.error(request, message)
        return redirect(request.META.get('HTTP_REFERER', '/'))

    vacancy = get_object_or_404(Vacancy, id=vacancy_id)
    user = request.user

    # Check if user already applied
    if Application.objects.filter(applicant=user, vacancy=vacancy).exists():
        return redirect_with_error('You have already applied for this Position.')

    # Check basic education and resume existence
    if not BasicEducation.objects.filter(user=user).exists() or not Resume.objects.filter(user=user).exists():
        if user.access_level != 5:
            return redirect_with_error('Update your Basic information / academic Details to apply !!')

    # Check college/university details
    if vacancy.college_required and not FurtherStudies.objects.filter(user=user).exists():
        return redirect_with_error('College/University Details are required for this position')

    # Check required certifications
    if vacancy.certifications_required and not Certification.objects.filter(user=user).exists():
        return redirect_with_error('Certifications are required for this position')

    # Check professional memberships
    if vacancy.membership_required and not Membership.objects.filter(user=user).exists():
        return redirect_with_error('Professional Membership required for this position')

    # Check number of referees
    if Referee.objects.filter(user=user).count() < 3:
        if user.access_level != 5:
            return redirect_with_error('You don\'t have enough referees to apply. 3 Referees are required.')

    user_work_experience = WorkExperience.objects.filter(user=user)
    total_work_experience_years, total_work_experience_months = calculate_work_experience(
        user_work_experience)

    min_educational_level = vacancy.min_educational_level

    resume = Resume.objects.filter(user=user).first()
    user_educational_level = resume.educational_level if resume else None

    if not user_educational_level:
        return redirect_with_error('Missing Highest Education Level, Update College/University to apply')

    qualify_educational_level = user_educational_level.index >= min_educational_level.index
    total_work_experience_years_fraction = total_work_experience_years + \
        total_work_experience_months / 12.0
    qualify_work_experience = total_work_experience_years_fraction >= vacancy.min_work_experience

    disqualification_reason = "Not Available"
    if not qualify_educational_level and not qualify_work_experience:
        disqualification_reason = "Does not meet required education level and work experience"
    elif not qualify_educational_level:
        disqualification_reason = "Does not meet required education level"
    elif not qualify_work_experience:
        disqualification_reason = "Does not have enough work experience"

    highest_educational_level = user_educational_level.name if user_educational_level else None

    application = Application(
        applicant=user,
        vacancy=vacancy,
        highest_educational_level=highest_educational_level,
        work_experience=total_work_experience_years,
        months=total_work_experience_months,
        qualify=qualify_educational_level and qualify_work_experience,
        disqualification_reason=disqualification_reason,
    )

    try:
        reference_number = generate_reference_number(vacancy)
        application.reference_number = reference_number
        application.full_clean()
        application.save()

        try:
            send_application_confirmation_email(
                user, vacancy, reference_number)
        except Exception as e:
            messages.warning(
                request, 'Application submitted successfully, but there was an error sending the confirmation email.')

        request.session['application_id'] = application.id
        return redirect('vacancies:apply_succ')

    except ValidationError as e:
        messages.error(request, e.message_dict)
        return redirect_with_error('There was an error with your application. Please try again.')


def application_succ(request):
    application_id = request.session.get('application_id')

    if application_id:
        application = get_object_or_404(Application, id=application_id)

        vacancy_title = application.vacancy.title
        reference_number = application.reference_number

        context = {
            'vacancy_title': vacancy_title,
            'reference_number': reference_number,
        }
        return render(request, 'vacancies/apply_succ.html', context)


@login_required
def applications(request):

vacancies/templates/vacancies/apply_succ.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="#" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-check-circle fa-5x text-success"></i>
                                        </a>
                                    </div>
                                    <div>
                                        {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'success' %}
                                                <div class="alert alert-success alert-dismissible" role="alert">
                                                   
                                                    {{ message|safe|escape }}
                                                </div>
                                            {% elif message.tags == 'error' %}
                                                <div class="alert alert-danger alert-dismissible" role="alert">
                                                   
                                                    {{ message|safe }}
                                                </div>
                                            {% elif message.tags == 'info' %}
                                                <div class="alert alert-info alert-dismissible" role="alert">
                                                   
                                                    {{ message|safe|escape }}
                                                </div>
                                         
                                    <div class="alert alert-warning alert-dismissible" role="alert">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        {{ message|safe|escape }}
                                    </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    </div>
                                    <h1 class="h5 mb-1 text-center">Application succesful</h1>
                                    <p class="text-muted text-center">Your application for <b> {{vacancy_title}}</b> was succesful with Reference number <b>{{reference_number}}</b></p>
                                    <p class="text-muted mb-4 text-center">Only shortlisted applicants will be Contacted</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    setTimeout(function() {
        window.location.href = "{% url 'vacancies:applications' %}";
    }, 3000);
</script>
{% endblock content %}

vacancies/templates/vacancies/job.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <!-- Carousel Section -->
    <div class="carousel-container">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div style="position: relative;">
                        <img class="d-block img-fluid" src="{{ job.job_type.banner.url }}" alt="{{ job_type.name }} Banner" style="width: 100%;">
                        <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5); z-index: 1;"></div>
                    </div>
                    <div class="carousel-caption mt-md-4 d-none d-md-block">
                        <h3 class="text-white">{{ job.title }} - {{ job.ref }}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Page Content -->
    <div class="page-content">
        <div class="container-fluid">
            {% if user.is_authenticated %}
                <div class="row mb-3">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs">
                            {% if user.access_level != 5 %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:bio_info' %}">Bio Information</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:high_school' %}">Basic Education</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:college' %}">College/University</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:certs' %}">Certifications</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:memberships' %}">Memberships</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:experience' %}">Work Experience</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:refs' %}">Referees</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'main:resume' %}">Review</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:career_objective' %}">Executive Summary</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:college' %}">Basic Education</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:college' %}">College/University</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:certs' %}">Professional Certificates</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:memberships' %}">Professional Memberships</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:experience' %}">Work Experience</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main:refs' %}">Referees</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'main:resume' %}">Review</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            {% endif %}

            <!-- Job Details Section -->
            <div class="card p-3">
                <h2 class="card-title text-center" style="color: #FD7E14;">Vacancy Details - {{ job.title }} - {{ job.ref }}</h2>
                <div>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message|safe|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="row mt-3">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="card-title">Job Summary</h4>
                                <p class="card-subtitle mb-4">{{ job.description|safe }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="card-title">Responsibilities</h4>
                                <p class="card-subtitle mb-4">{{ job.position_responsibilities|safe }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Nature of Job:</h4></div>
                                    <div class="col-md-6">{{ job.job_type }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Job Discipline:</h4></div>
                                    <div class="col-md-6">{{ job.job_discipline }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Reports to:</h4></div>
                                    <div class="col-md-6">{{ job.reports_to }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Min Education Level:</h4></div>
                                    <div class="col-md-6">{{ job.min_educational_level }}</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Experience:</h4></div>
                                    <div class="col-md-6">{{ job.min_work_experience }} years</div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6"><h4 class="card-title">Application End:</h4></div>
                                    <div class="col-md-6">{{ job.date_close }}</div>
                                </div>
                            </div>
                        </div>

                        {% if job.certifications_required or job.college_required or job.membership_required %}
                            <div class="card mt-3">
                                <div class="card-body">
                                    <h4 class="card-title">Additional Requirements</h4>
                                    {% if job.certifications_required %}
                                        <p>Relevant certifications Required</p>
                                    {% endif %}
                                    {% if job.college_required %}
                                        <p>College/Degree Certificates Required</p>
                                    {% endif %}
                                    {% if job.membership_required %}
                                        <p>Relevant Membership Certificates Required</p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>

                <!-- Terms Acceptance and Apply Button -->
                <div class="text-center mt-3">
                    {% if terms.accepted %}
                        <a href="{% url 'users:terms_acceptance' %}">
                            <i class="fas btn-primary active fa-check-square"></i>
                        </a>
                        <a class="ml-2" href="{% url 'main:terms' %}">Terms and Conditions Accepted</a>
                    {% else %}
                        <a href="{% url 'users:terms_acceptance' %}">
                            <i class="btn btn-danger active far fa-square"></i>
                        </a>
                        <a class="ml-2" href="{% url 'main:terms' %}">Accept Terms and Conditions</a>
                    {% endif %}
                </div>

                <div class="text-center mt-2 mb-2">
                    {% if user.is_authenticated %}
                        {% if terms.accepted %}
                            <a href="{% url 'vacancies:apply' vacancy_id=job.id %}" class="btn btn-lg btn-primary active">
                                Apply this Job Now <i class="fas fa-arrow-circle-right text-white"></i>
                            </a>
                        {% else %}
                            <button class="btn btn-lg btn-primary" disabled>
                                Apply this Job Now <i class="fas fa-arrow-circle-right text-white"></i>
                            </button>
                            <small class="form-text text-danger">Accept terms and conditions to apply</small>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'users:login' %}" class="btn btn-primary mt-3">Login to Apply</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}