ejobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = 'error_handling.views.custom_404'
handler500 = 'error_handling.views.custom_500'


urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path('index/<int:pk>/', views.job_type_detail, name='vacs'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path("bio_info/", views.bio_info, name="bio_info"),
    path('basic_info/<int:user_id>/', views.basic_info, name='basic_info'),
    path('basic_academic/', views.basic_academic, name='basic_academic'),
    path('high_school/', views.high_school, name='high_school'),
    path('college/', views.college, name='college'),
    path('update_basic_education/<int:instance_id>/',
         views.update_basic_academic, name='update_basic_education'),
    path('delete_basic_education/<int:instance_id>/',
         views.delete_basic_academic, name='delete_basic_education'),
    path('further_studies/', views.further_studies, name='further_studies'),
    path('update_further_studies/<int:instance_id>/',
         views.update_further_studies, name='update_further_studies'),
    path('delete_further_studies/<int:instance_id>/',
         views.delete_further_studies, name='delete_further_studies'),
    path('certs/', views.certs, name='certs'),
    path('certification/', views.certification, name='certification'),
    path('update_certification/<int:instance_id>/',
         views.update_certification, name='update_certification'),
    path('delete_certification/<int:instance_id>/',
         views.delete_certification, name='delete_certification'),
    path('memberships/', views.memberships, name='memberships'),
    path('membership/', views.membership, name='membership'),
    path('update_membership/<int:instance_id>/',
         views.update_membership, name='update_membership'),
    path('delete_membership/<int:instance_id>/',
         views.delete_membership, name='delete_membership'),
    path('experience/', views.experience, name='experience'),
    path('work_experience/', views.work_experience, name='work_experience'),
    path('update_work_experience/<int:instance_id>/',
         views.update_work_experience, name='update_work_experience'),
    path('delete_work_experience/<int:instance_id>/',
         views.delete_work_experience, name='delete_work_experience'),
    path('referees/', views.referees, name='referees'),
    path('refs/', views.refs, name='refs'),
    path('update_referees/<int:instance_id>/',
         views.update_referee, name='update_referee'),
    path('delete_referee/<int:instance_id>/',
         views.delete_referee, name='delete_referee'),
    path('career_objective/', views.career_objective, name='career_objective'),
    path('update_career_objective/', views.update_career_objective,
         name='update_career_objective'),
      path('resume/', views.resume, name='resume'),
    path('terms/', views.terms, name='terms'),
    path('staff/', views.staff, name='staff_profile'),
    path('update_educational_level/',
         views.update_educational_level, name='edu_level'),
    path('how_to_apply/', views.how, name='how'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path('login/', views.custom_login, name='login'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('secure/<uidb64>/<token>', views.secure, name='secure'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path('create_staff/', views.create_access_level_5_user, name='create_staff'),
    path("staff_no/", views.staff_no, name="staff_no"),
    path("permission_denied/", views.not_allowed, name="denials"),
    path("f_pass", views.f_pass, name="f_pass"),
    path('del_user/<int:user_id>', views.delete_user, name='del_user'),
    path('terms_acceptance/',
         views.terms_acceptance, name='terms_acceptance'),
    path('vacancy/<int:vacancy_id>/terms_acceptance/',
         views.internal_terms_acceptance, name='internal_terms_acceptance'),
    path('internship/<int:vacancy_id>/terms_acceptance/',
         views.internship_terms_acceptance, name='internship_terms_acceptance'),
    path('attachment/<int:vacancy_id>/terms_acceptance/',
         views.attachment_terms_acceptance, name='attachment_terms_acceptance'),
]

vacancies/urls.py
from django.urls import path
from . import views

app_name = 'vacancies'
urlpatterns = [
    path('job/<int:vacancy_id>/', views.job, name='job'),
    path("internships", views.internships, name="internships"),
    path('internship/<int:vacancy_id>/', views.internship, name='internship'),
    path("attachments", views.attachments, name="attachments"),
    path('attachment/<int:vacancy_id>/', views.attachment, name='attachment'),
    path('apply/<int:vacancy_id>/', views.apply, name='apply'),
    path('applications/', views.applications, name='applications'),
    path('reapply/<int:application_id>/',
         views.reapply_application, name='recall_application'),
    path('delete/<int:application_id>/',
         views.delete_application, name='delete_application'),
    path("internal", views.internal, name="internal"),
    path('internal_detail/<int:vacancy_id>/',
         views.internal_detail, name='internal_detail'),
    path('application/success/', views.application_succ, name='apply_succ'),
    path('vacancies/apply_fail', views.apply_fail, name='apply_fail'),

]

users/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
import logging
from .models import Staff
import re
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, login
from .forms import *
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .decorators import user_not_authenticated
from django.contrib.auth import authenticate, login
from .decorators import *
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from .forms import *
from django.db.models.query_utils import Q
from django.contrib.auth.decorators import user_passes_test
import random
import string
from urllib.parse import urlencode
from django.http import QueryDict
from vacancies.models import *
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import check_password
from main.mails import *
from django.core.mail import BadHeaderError
from django.core.exceptions import ImproperlyConfigured


def is_system_admin(user):
    return user.is_superuser or (user.access_level == 'system admin')


def not_authorized(request):
    return render(
        request,
        template_name="admin/not_authorized.html"
    )


@user_not_authenticated
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            id_number = form.cleaned_data.get('id_number')

            # Custom validation for id_number
            if not id_number:
                form.add_error('id_number',
                               'Id Number Required')

            elif len(id_number) != 8:
                form.add_error('id_number',
                               'Must be 8 Digits Long')

            elif id_number == '00000000':
                form.add_error('id_number',
                               'Id Number Cannot be 00000000')

            else:
                user = form.save(commit=False)
                user.is_active = False
                user.save()

                if activateEmail(request, user, form.cleaned_data.get('email')):
                    success_message = f'Dear {user.username}, an activation link has been sent to {form.cleaned_data.get("email")}. Follow the instructions to activate your account.'
                    messages.success(request, success_message)
                else:
                    messages.info(
                        request, "Registration was successful, but there was a problem sending the activation link to your email. Please contact the admin."
                    )

                return redirect('users:login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name="users/register.html",
        context={"form": form}
    )


def activateEmail(request, user, to_email):
    subject = 'KenGen Careers Portal - User Registration.'
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = account_activation_token.make_token(user)
    domain = get_current_site(request).domain
    protocol = 'https' if request.is_secure() else 'http'

    message = render_to_string('users/template_activate_account.html', {
        'user': user,
        'domain': domain,
        'uid': uid,
        'token': token,
        'protocol': protocol
    })

    if send_custom_email(subject, message, [to_email]):
        return True
    else:
        return False


def sendPasswordResetLink(request, user, to_email):
    subject = 'KenGen Careers Portal - Password Reset Request..'
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = account_activation_token.make_token(user)
    reset_link = f"{'https' if request.is_secure() else 'http'}://{get_current_site(request).domain}{reverse('users:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})}"
    message = f"""
    Dear {user.username},

    We received a request to reset your password on the KenGen Careers Portal. Follow the link below to reset your password.

    {reset_link}

    If you did not request a password reset, please ignore this email.

    Sincerely,
    KenGen Careers
    """
    if send_custom_email(subject, message, [to_email]):
        return True
    else:
        return False


def activate(request, uidb64, token):
    User = get_user_model()
    success_message = error_message = None

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        success_message = 'Thank you for your email confirmation. You can Now Login.'
        messages.success(request, success_message)
        return redirect('users:login')

    else:
        error_message = 'Activation link is invalid, or has expired, Please Conduct admin for more Details'
        messages.error(request, error_message)
        return redirect('users:login')


def secure(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        # Log in the user
        login(request, user)

        messages.success(request, 'Password Updated succesfully.')
        return redirect('users:password_change')
    else:
        messages.error(request, 'Password change link is invalid!')

    return redirect('/')


def generate_random_password(length=10):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password


@user_not_authenticated
def custom_login(request):
    next_url = request.GET.get('next')

    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Check if the user's access level is 5 or if the user is a superuser
                if user.access_level == 5 or user.is_superuser:
                    messages.error(
                        request, "Access denied. Use the Internal Recruitment Portal")
                else:
                    login(request, user)
                    messages.success(
                        request, f"Success, You are logged in as {user.username}")

                    if next_url:
                        return redirect(next_url)
                    else:
                        return redirect("/")
            else:
                messages.error(request, "Invalid username or password")
        else:
            for error in list(form.errors.values()):
                messages.error(request, " ".join(error))
    else:
        form = UserLoginForm()

    return render(
        request=request,
        template_name="users/login.html",
        context={"form": form}
    )


def sendActivationLink(request, user, to_email):
    subject = 'KenGen Careers Portal - User Register'
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = account_activation_token.make_token(user)
    activation_link = f"{'https' if request.is_secure() else 'http'}://{get_current_site(request).domain}{reverse('users:activate', kwargs={'uidb64': uid, 'token': token})}"
    message = f"""
    Dear {user.username},

    This is an email to secure your account through the Kengen Career Portal. Follow the link below to activate your account.

    {activation_link}

    If you did not make this request, you can simply ignore this email.

    Sincerely,
    Kengen Careers
    """

    send_custom_email(subject, message, [to_email], bcc=[
                      'nelson.masibo@kenyaweb.com'])

    messages.success(
        request, f'Dear <b>{user.username}</b>, an email has been sent to {to_email}')


def profile(request, user_id):
    if request.user.id != user_id:
        messages.error(request, "UnAuthorized Access")
        return redirect(request.META.get('HTTP_REFERER', '/'))

    user = get_object_or_404(get_user_model(), id=user_id)

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            user_form = form.save()
            messages.success(
                request, 'Your profile has been updated!')
            return redirect('users:profile', user_form.id)

        for error in list(form.errors.values()):
            messages.error(request, error)
    else:
        form = UserUpdateForm(instance=user)

    return render(request, 'users/profile.html', context={'form': form})


@login_required
def password_change(request):
    error_messages = []
    user = request.user

    if request.method == 'POST':
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():

users/templates/users/f_pass.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 100px !important;">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="#" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-user-alt" style="font-size: 50px; color: #703B97;"></i>
                                        </a>
                                    </div>
                                    <h4>Check Your Email</h4>
                                    <div>
                                        {% if messages %}
                                            {% for message in messages %}
                                                {% if message.tags == 'success' %}
                                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'error' %}
                                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'info' %}
                                                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'warning' %}
                                                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                  

                                    <p>Remember to check your Spam folder if you can't Find the Email in your Inbox</p>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        setTimeout(function() {
            window.location.href = "{% url 'users:login' %}";
        }, 5000);
    </script>
{% endblock content %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 100px !important;">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-8">
            <div class="d-flex align-items-center min-vh-100 justify-content-center">
                <div class="w-100 bg-white shadow-lg rounded">
                    <div class="row no-gutters">
                        <!-- Image Column (Visible only on md and larger screens) -->
                        <div class="col-md-6 p-0 d-none d-md-flex align-items-stretch">
                            <img src="{% static 'dashboard/images/auth/login.jpg' %}" class="img-fluid rounded-start img-cover" alt="login banner">
                        </div>

                        <!-- Form Column -->
                        <div class="col-md-6 p-5">
                            <div class="text-center mb-4">
                                <a href="#" class="text-dark font-size-22 font-family-secondary">
                                    <i class="fas fa-user-alt" style="font-size: 30px; color: #703B97"></i>
                                </a>
                            </div>
                            <p class="text-muted mb-3 mt-3 text-center">SIGN IN</p>

                            <div>
                                {% if messages %}
                                    {% for message in messages %}
                                        {% if message.tags == 'success' %}
                                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                {{ message|safe|escape }}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% elif message.tags == 'error' %}
                                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                {{ message|safe|escape }}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% elif message.tags == 'info' %}
                                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                                {{ message|safe|escape }}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% elif message.tags == 'warning' %}
                                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                {{ message|safe|escape }}
                                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>

                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.username|as_crispy_field }}
                                </div>
                                <div class="form-group position-relative mt-4">
                                    {{ form.password|as_crispy_field }}
                                    <span class="position-absolute top-50 end-0 translate-middle-y me-3" onclick="togglePasswordVisibility()">
                                        <i id="toggleIcon" class="fas fa-eye" style="cursor: pointer;"></i>
                                    </span>
                                </div>
                                <div class="form-group mt-4 text-center">
                                    <button class="btn btn-primary" type="submit">Login</button>
                                </div>
                            </form>

                            <div class="row mt-4">
                                <div class="col-12 text-center">
                                    <p class="text-muted mb-2">
                                        Forgot your password?
                                        <a href="{% url 'users:password_reset' %}" class="font-weight-medium ml-1" style="color: #703B97;">RESET</a>
                                    </p>
                                    <p class="text-muted mb-0">
                                        Don't have an account? 
                                       
                                        <a href="{% url 'users:register' %}" class="font-weight-medium ml-1" style="color: #703B97;">SIGN UP</a>
                                    </p>
                                </div> 
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/new_account.html
{% autoescape off %}
Hi {{ user.username }},

An account was successfully created for you at:

URL: http://{{ domain }}{% url 'vacancies:internal'%}

Here are your account details:
Username: {{ user.username }}
Password: {{ password }}

Please visit the URL to log in and change your password for you to apply new roles on the portal, All the best.

Login URL: http://{{ domain }}{% url 'users:login' %}

{% endautoescape %}

users/templates/users/password_change.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 100px !important;">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <a href="#" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-user-alt" style="font-size: 50px; color: #703B97;"></i>
                                        </a>
                                    </div>
                                    <h1 class="h5 mb-1 text-center">New Password</h1>

                                    <div>
                                        {% if messages %}
                                            {% for message in messages %}
                                                {% if message.tags == 'success' %}
                                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'error' %}
                                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'info' %}
                                                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% elif message.tags == 'warning' %}
                                                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                        {{ message|safe|escape }}
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                  
                                    
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-12">
                                            {{ form.new_password1|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            {{ form.new_password2|as_crispy_field }}
                                        </div>
                                    </div>
                                    
                                    <div class="form-group mt-2 text-center">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </div>
                                </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/secure_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your Password Change Request:

http://{{ domain }}{% url 'users:secure' uidb64=uid token=token %}
{% endautoescape %}

Please ignore the email if you did not request for password change

users/templates/users/template_activate_account.html
{% autoescape off %}
Dear {{ user.username }},

This is an email after you registered with KenGen Careers Portal. If this email is not meant for you, kindly trash it.

To activate your account, Please click on the link below

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

Regards,
KenGen Careers Portal

{% endautoescape %}