ejobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = 'error_handling.views.custom_404'
handler500 = 'error_handling.views.custom_500'


urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path('index/<int:pk>/', views.job_type_detail, name='vacs'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path("bio_info/", views.bio_info, name="bio_info"),
    path('basic_info/<int:user_id>/', views.basic_info, name='basic_info'),
    path('basic_academic/', views.basic_academic, name='basic_academic'),
    path('high_school/', views.high_school, name='high_school'),
    path('college/', views.college, name='college'),
    path('update_basic_education/<int:instance_id>/',
         views.update_basic_academic, name='update_basic_education'),
    path('delete_basic_education/<int:instance_id>/',
         views.delete_basic_academic, name='delete_basic_education'),
    path('further_studies/', views.further_studies, name='further_studies'),
    path('update_further_studies/<int:instance_id>/',
         views.update_further_studies, name='update_further_studies'),
    path('delete_further_studies/<int:instance_id>/',
         views.delete_further_studies, name='delete_further_studies'),
    path('certs/', views.certs, name='certs'),
    path('certification/', views.certification, name='certification'),
    path('update_certification/<int:instance_id>/',
         views.update_certification, name='update_certification'),
    path('delete_certification/<int:instance_id>/',
         views.delete_certification, name='delete_certification'),
    path('memberships/', views.memberships, name='memberships'),
    path('membership/', views.membership, name='membership'),
    path('update_membership/<int:instance_id>/',
         views.update_membership, name='update_membership'),
    path('delete_membership/<int:instance_id>/',
         views.delete_membership, name='delete_membership'),
    path('experience/', views.experience, name='experience'),
    path('work_experience/', views.work_experience, name='work_experience'),
    path('update_work_experience/<int:instance_id>/',
         views.update_work_experience, name='update_work_experience'),
    path('delete_work_experience/<int:instance_id>/',
         views.delete_work_experience, name='delete_work_experience'),
    path('referees/', views.referees, name='referees'),
    path('refs/', views.refs, name='refs'),
    path('update_referees/<int:instance_id>/',
         views.update_referee, name='update_referee'),
    path('delete_referee/<int:instance_id>/',
         views.delete_referee, name='delete_referee'),
    path('career_objective/', views.career_objective, name='career_objective'),
    path('update_career_objective/', views.update_career_objective,
         name='update_career_objective'),
      path('resume/', views.resume, name='resume'),
    path('terms/', views.terms, name='terms'),
    path('staff/', views.staff, name='staff_profile'),
    path('update_educational_level/',
         views.update_educational_level, name='edu_level'),
    path('how_to_apply/', views.how, name='how'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path('login/', views.custom_login, name='login'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('secure/<uidb64>/<token>', views.secure, name='secure'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path('create_staff/', views.create_access_level_5_user, name='create_staff'),
    path("staff_no/", views.staff_no, name="staff_no"),
    path("permission_denied/", views.not_allowed, name="denials"),
    path("f_pass", views.f_pass, name="f_pass"),
    path('del_user/<int:user_id>', views.delete_user, name='del_user'),
    path('terms_acceptance/',
         views.terms_acceptance, name='terms_acceptance'),
    path('vacancy/<int:vacancy_id>/terms_acceptance/',
         views.internal_terms_acceptance, name='internal_terms_acceptance'),
    path('internship/<int:vacancy_id>/terms_acceptance/',
         views.internship_terms_acceptance, name='internship_terms_acceptance'),
    path('attachment/<int:vacancy_id>/terms_acceptance/',
         views.attachment_terms_acceptance, name='attachment_terms_acceptance'),
]

vacancies/urls.py
from django.urls import path
from . import views

app_name = 'vacancies'
urlpatterns = [
    path('job/<int:vacancy_id>/', views.job, name='job'),
    path("internships", views.internships, name="internships"),
    path('internship/<int:vacancy_id>/', views.internship, name='internship'),
    path("attachments", views.attachments, name="attachments"),
    path('attachment/<int:vacancy_id>/', views.attachment, name='attachment'),
    path('apply/<int:vacancy_id>/', views.apply, name='apply'),
    path('applications/', views.applications, name='applications'),
    path('reapply/<int:application_id>/',
         views.reapply_application, name='recall_application'),
    path('delete/<int:application_id>/',
         views.delete_application, name='delete_application'),
    path("internal", views.internal, name="internal"),
    path('internal_detail/<int:vacancy_id>/',
         views.internal_detail, name='internal_detail'),
    path('application/success/', views.application_succ, name='apply_succ'),
    path('vacancies/apply_fail', views.apply_fail, name='apply_fail'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import os
from django_countries.fields import CountryField
from datetime import *
from django.db.models import F, Max


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    ACCESS_LEVEL_CHOICES = (
        (0, 'Job Seeker'),
        (1, 'System Admin'),
        (2, 'HR'),
        (3, 'HR Interns'),
        (4, 'HR Attachments'),
        (5, 'staffs'),
    )
    FUNCTION_CHOICES = (
        (0, 'No Previllages'),
        (1, 'Hr-General'),
        (2, 'Hr-Post Jobs(Internal/External)'),
        (3, 'Hr-Post Internship/Attachment'),
        (4, 'Hr-Publsh Jobs(Internal/External)'),
        (5, 'Hr-Publish Internship/Attachment'),
        (6, 'Hr-Edit Jobs(Internal/External)'),
        (7, 'Hr-Edit Internship/Attachment'),
        (8, 'Hr-Delete Jobs(Internal/External)'),
        (9, 'Hr-Delete Internship/Attachment'),
        (10, 'ICT'),

    )

    staff_no = models.CharField(max_length=20, unique=True, null=True)
    trials = models.PositiveIntegerField(default=4)
    is_restricted = models.BooleanField(default=False)

    access_level = models.PositiveIntegerField(
        choices=ACCESS_LEVEL_CHOICES,
        default=0,
    )
    function = models.PositiveIntegerField(
        choices=FUNCTION_CHOICES,
        default=0,
    )

    id_number = models.PositiveIntegerField(
        unique=True, blank=True, null=True)

    def image_upload_to(self, filename):
        return os.path.join('Users', self.username, filename)

    profile = models.ImageField(
        default='default/user.jpg',
        upload_to=image_upload_to
    )

    def __str__(self):
        return f"{self.id}"


class ProfileUpdate(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    password_changed = models.BooleanField(default=False)

    def __str__(self):
        return f"Profile Update for {self.user.username}"


class Staff(models.Model):
    staff_no = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, null=True)

    def __str__(self):
        return self.staff_no


class UserAccessLog(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.timestamp}"


class AdminAccessLog(models.Model):
    admin_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.admin_user.username} - {self.timestamp}"


class Ethnicity(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class EducationalLevel(models.Model):
    name = models.CharField(max_length=255)
    index = models.PositiveIntegerField(unique=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.pk:  # Only on creation, not on updates
            max_index = EducationalLevel.objects.aggregate(Max('index'))[
                'index__max']
            self.index = (max_index or 0) + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['index']


class FieldOfStudy(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class CertifyingBody(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Certificate(models.Model):
    name = models.CharField(max_length=255)
    certifying_body = models.ForeignKey(
        CertifyingBody, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class MaritalStatus(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class County(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Counties"


class Resume(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    # Basic Information
    full_name = models.CharField(max_length=255, blank=True, null=True)
    email_address = models.EmailField(blank=True, null=True, unique=True)
    phone = models.CharField(max_length=10, blank=True, null=True, unique=True)
    id_number = models.PositiveIntegerField(
        unique=True, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    country_of_birth = CountryField(blank=True, null=True)
    country_of_residence = CountryField(blank=True, null=True)
    county_of_birth = models.CharField(
        max_length=255, blank=True, null=True)  # Changed field
    county_of_residence = models.CharField(
        max_length=255, blank=True, null=True)
    ethnicity = models.ForeignKey(
        Ethnicity, on_delete=models.SET_NULL, blank=True, null=True)

    religeon = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=50, blank=True, null=True)
    DISABILITY_CHOICES = (
        (True, 'Yes'),
        (False, 'No'),
    )
    disability = models.BooleanField(
        choices=DISABILITY_CHOICES, default=False, blank=True, null=True)
    disability_number = models.CharField(max_length=20, blank=True, null=True)

    marital_status = models.CharField(max_length=50, blank=True, null=True)

    educational_level = models.ForeignKey(
        EducationalLevel, on_delete=models.SET_NULL, blank=True, null=True)
    field_of_study = models.ForeignKey(
        FieldOfStudy, on_delete=models.SET_NULL, blank=True, null=True)
    date_registered = models.DateTimeField(auto_now_add=True)

    age = models.PositiveIntegerField(blank=True, null=True, editable=False)

    @property
    def calculate_age(self):
        if self.dob:
            today = date.today()
            birth_date = self.dob
            age = today.year - birth_date.year - \
                ((today.month, today.day) < (birth_date.month, birth_date.day))
            return age
        return None

    def save(self, *args, **kwargs):
        self.age = self.calculate_age
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Resume for {self.user.username}"


class BasicEducation(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='basic_education')
    name_of_the_school = models.CharField(
        max_length=255, blank=True, null=True)
    certification_choices = (
        ('KCSE', 'Kenya Certificate of Secondary Education (KCSE)'),
        ('KCPE', 'Kenya Certificate of Primary Education (KCPE)'),
    )
    certification = models.CharField(
        max_length=10, choices=certification_choices, default='KCSE', blank=True, null=True)
    date_started = models.DateField(blank=True, null=True)
    date_ended = models.DateField(blank=True, null=True)
    grade_attained = models.CharField(max_length=10, blank=True, null=True)
    certificate = models.FileField(
        upload_to='certificates/{user_id}/{basic_education_id}/', blank=True, null=True)

    def __str__(self):
        return f"Basic Education for {self.user.username}"


class FurtherStudiesCertification(models.Model):
    certification_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.certification_name}"


class FurtherStudies(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='further_studies')
    institution_name = models.CharField(max_length=255, blank=True, null=True)
    certifications = models.ForeignKey(
        EducationalLevel, on_delete=models.SET_NULL, blank=True, null=True)
    course_undertaken = models.CharField(max_length=100, blank=True, null=True)
    date_started = models.DateField(blank=True, null=True)
    date_ended = models.DateField(blank=True, null=True)
    grade = models.CharField(max_length=100, blank=True, null=True)
    certificate = models.FileField(
        upload_to='certificates/{user_id}/{further_studies_id}/', blank=True, null=True)

    def __str__(self):
        return self.institution_name


class Membership(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
                             related_name='memberships', blank=True, null=True)
    membership_title = models.CharField(max_length=255, blank=True, null=True)
    membership_number = models.CharField(max_length=50, blank=True, null=True)
    membership_body = models.CharField(max_length=255, blank=True, null=True)
    date_joined = models.DateField(blank=True, null=True)
    certificate = models.FileField(
        upload_to='certificates/{user_id}/memberships/', blank=True, null=True)

    def __str__(self):
        return self.membership_title


class WorkExperience(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
                             related_name='work_experiences', blank=True, null=True)
    company_name = models.CharField(max_length=255, blank=True, null=True)
    position = models.CharField(max_length=255, blank=True, null=True)
    date_started = models.DateField(blank=True, null=True)
    date_ended = models.DateField(blank=True, null=True)
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_phone = models.CharField(max_length=20, blank=True, null=True)
    responsibilities = models.TextField(blank=True, null=True)
    currently_working = models.BooleanField(default=False)
    years = models.PositiveIntegerField(blank=True, null=True)

main/templates/main/experience.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div style="margin-top: 80px !important;">
       {% if user.is_authenticated %}
   <div class="quick-nav">
        <div class="row justify-content-center mb-0">
            <div class="col-12">
                <div class="custom-nav-header">
                    <ul class="nav nav-tabs custom-tabs flex-wrap justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'bio_info' %}active{% endif %}" href="{% url 'main:bio_info' %}">Bio Information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'high_school' %}active{% endif %}" href="{% url 'main:high_school' %}">Basic Education</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'college' %}active{% endif %}" href="{% url 'main:college' %}">College/University</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'certs' %}active{% endif %}" href="{% url 'main:certs' %}">Certifications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'memberships' %}active{% endif %}" href="{% url 'main:memberships' %}">Memberships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'experience' %}active{% endif %}" href="{% url 'main:experience' %}">Work Experience</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'refs' %}active{% endif %}" href="{% url 'main:refs' %}">Referees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'resume' %}active{% endif %}" href="{% url 'main:resume' %}">Review</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
  {% endif %}

       <div class="container" style="margin-top: 10px !important;">
        <div class="row mt-4">
            <div style="width: 100%;">
                <div style="border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; border-left: 4px solid #4F16A7;">
                    <h4 style="margin-top: 3px;">Work Experience</h4>
                    {% if all_fields %}
                    <p style="margin-bottom: 4px;" class="text-success"> Your Work Experience is updated</p>
                    {% else %}
                    <p style="margin-bottom: 4px;" class="text-warning"> Your Employment History is Incomplete</p>
                    {% endif %}
                </div>
            </div>    
        </div>
      
        <div class="card mt-4">
            <div class="card-body">
                <h2 class="mb-4 text-center" style="color: #FD7E14;">Work Experience Details</h2>
                <div>
                    {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success alert-dismissible" role="alert">
                               
                                {{ message|safe|escape }}
                            </div>
                        {% elif message.tags == 'error' %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                               
                                {{ message|safe }}
                            </div>
                        {% elif message.tags == 'info' %}
                            <div class="alert alert-info alert-dismissible" role="alert">
                               
                                {{ message|safe|escape }}
                            </div>
                     
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ message|safe|escape }}
                </div>
            {% endif %}
                {% endfor %}
            {% endif %}
                </div>
                {% if wx %}
                <div class="row mt-4">
                    <div class="col-xl-12">
                       <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Company</th>
                                    <th>Title</th>
                                    <th>Dates</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for experience in wx %}
                                    <tr>
                                        <td><a href="{% url 'main:update_work_experience' instance_id=experience.pk %}">{{ experience.company_name }}</a></td>
                                        <td>{{ experience.position }}</td>
                                        <td>{{ experience.date_started }} - {% if experience.date_ended %}{{ experience.date_ended }}{% else %}Current Job{% endif %}</td>
                                        <td>
                                            <a href="{% url 'main:update_work_experience' instance_id=experience.pk %}">Edit</a> |
                                            <a href="{% url 'main:delete_work_experience' instance_id=experience.pk %}" onclick="return confirmDeletion(this);">Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                       </div>
                    </div>
                </div>
            {% else %}
                <p class="text-center">No Work Experience Found</p>
            {% endif %}
            
            
            

                <div class="text-center mt-4">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary active">Back</a>
                    <a href="{% url 'main:work_experience' %}" class="btn btn-primary active ml-2">Add New</a>
                    {% if refs %}
                        <a href="{% url 'main:refs' %}" class="btn btn-primary active ml-2">Next</a>
                    {% else %}
                        <a href="{% url 'main:refs' %}" class="btn btn-primary active ml-2">Next</a>
                    {% endif %}
                </div>
            </div>
        </div>
       </div>
    </div>
{% endblock content %}

main/templates/main/high_school.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div style="margin-top: 80px !important;">
       {% if user.is_authenticated %}
   <div class="quick-nav">
        <div class="row justify-content-center mb-0">
            <div class="col-12">
                <div class="custom-nav-header">
                    <ul class="nav nav-tabs custom-tabs flex-wrap justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'bio_info' %}active{% endif %}" href="{% url 'main:bio_info' %}">Bio Information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'high_school' %}active{% endif %}" href="{% url 'main:high_school' %}">Basic Education</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'college' %}active{% endif %}" href="{% url 'main:college' %}">College/University</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'certs' %}active{% endif %}" href="{% url 'main:certs' %}">Certifications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'memberships' %}active{% endif %}" href="{% url 'main:memberships' %}">Memberships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'experience' %}active{% endif %}" href="{% url 'main:experience' %}">Work Experience</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'refs' %}active{% endif %}" href="{% url 'main:refs' %}">Referees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'resume' %}active{% endif %}" href="{% url 'main:resume' %}">Review</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
  {% endif %}


      <div class="container" style="margin-top: 10px !important;">
        <div class="row mt-4">
            <div style="width: 100%;">
                <div style="border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; border-left: 4px solid #4F16A7;">
                    <h4 style="margin-top: 3px;">Basic Education</h4>
                    {% if all_fields %}
                    <p style="margin-bottom: 4px;" class="text-success"> Your Basic Education Information is Complete</p>
                    {% else %}
                    <p style="margin-bottom: 4px;" class="text-warning"> Your Basic Education Information is Incomplete</p>
                    {% endif %}
                </div>
            </div>    
        </div>
      
        <div class="card mt-4">
            <div class="card-body">
                <h2 class="mb-4 text-center" style="color: #FD7E14;">Basic Education Information</h2>
                <div>
                    {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success alert-dismissible" role="alert">
                               
                                {{ message|safe|escape }}
                            </div>
                        {% elif message.tags == 'error' %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                               
                                {{ message|safe }}
                            </div>
                        {% elif message.tags == 'info' %}
                            <div class="alert alert-info alert-dismissible" role="alert">
                               
                                {{ message|safe|escape }}
                            </div>
                     
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ message|safe|escape }}
                </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </div>
                {% if be %}
                <div class="row col-xl-12">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped responsive">
                                <thead>
                                    <tr>
                                        <th>Schoolchool</th>
                                        <th>Certification</th>
                                        <th>Date Dates</th>
                                        <th>Grade</th>
                                        <th>Certificate</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for education_instance in be %}
                                        <tr>
                                            <td>{{ education_instance.name_of_the_school }}</td>
                                            <td>{{ education_instance.get_certification_display }}</td>
                                            <td>{{ education_instance.date_started }} - {{ education_instance.date_ended }}</td>
                                           
                                            <td>{{ education_instance.grade_attained }}</td>
                                            <td>
                                                {% if education_instance.certificate %}
                                                    <a href="{{ education_instance.certificate.url }}" target="_blank">View Certificate</a>
                                                {% else %}
                                                    No certificate uploaded
                                                {% endif %}
                                            </td>
                                            <td>
                                                <a href="{% url 'main:update_basic_education' education_instance.pk %}">Edit</a> |
                                                <a href="{% url 'main:delete_basic_education' education_instance.pk %}" onclick="return confirmDeletion(this);">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
            {% else %}
                <p class="text-center">Your Basic Education Details are Missing</p>
            {% endif %}
            

                <div class="text-center mt-4">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary active">Back</a>
                    <a href="{% url 'main:basic_academic' %}" class="btn btn-primary active ml-2">Add New</a>
                   
                   
                        <a href="{% url 'main:college' %}" class="btn btn-primary active ml-2">Next</a>
                   
                </div>
            </div>
        </div>
      </div>
    </div>


{% endblock content %}