ejobs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

handler404 = 'error_handling.views.custom_404'
handler500 = 'error_handling.views.custom_500'


urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path('index/<int:pk>/', views.job_type_detail, name='vacs'),
    path('job/<int:job_id>/', views.job_detail, name='job_detail'),
    path("bio_info/", views.bio_info, name="bio_info"),
    path('basic_info/<int:user_id>/', views.basic_info, name='basic_info'),
    path('basic_academic/', views.basic_academic, name='basic_academic'),
    path('high_school/', views.high_school, name='high_school'),
    path('college/', views.college, name='college'),
    path('update_basic_education/<int:instance_id>/',
         views.update_basic_academic, name='update_basic_education'),
    path('delete_basic_education/<int:instance_id>/',
         views.delete_basic_academic, name='delete_basic_education'),
    path('further_studies/', views.further_studies, name='further_studies'),
    path('update_further_studies/<int:instance_id>/',
         views.update_further_studies, name='update_further_studies'),
    path('delete_further_studies/<int:instance_id>/',
         views.delete_further_studies, name='delete_further_studies'),
    path('certs/', views.certs, name='certs'),
    path('certification/', views.certification, name='certification'),
    path('update_certification/<int:instance_id>/',
         views.update_certification, name='update_certification'),
    path('delete_certification/<int:instance_id>/',
         views.delete_certification, name='delete_certification'),
    path('memberships/', views.memberships, name='memberships'),
    path('membership/', views.membership, name='membership'),
    path('update_membership/<int:instance_id>/',
         views.update_membership, name='update_membership'),
    path('delete_membership/<int:instance_id>/',
         views.delete_membership, name='delete_membership'),
    path('experience/', views.experience, name='experience'),
    path('work_experience/', views.work_experience, name='work_experience'),
    path('update_work_experience/<int:instance_id>/',
         views.update_work_experience, name='update_work_experience'),
    path('delete_work_experience/<int:instance_id>/',
         views.delete_work_experience, name='delete_work_experience'),
    path('referees/', views.referees, name='referees'),
    path('refs/', views.refs, name='refs'),
    path('update_referees/<int:instance_id>/',
         views.update_referee, name='update_referee'),
    path('delete_referee/<int:instance_id>/',
         views.delete_referee, name='delete_referee'),
    path('career_objective/', views.career_objective, name='career_objective'),
    path('update_career_objective/', views.update_career_objective,
         name='update_career_objective'),
      path('resume/', views.resume, name='resume'),
    path('terms/', views.terms, name='terms'),
    path('staff/', views.staff, name='staff_profile'),
    path('update_educational_level/',
         views.update_educational_level, name='edu_level'),
    path('how_to_apply/', views.how, name='how'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path('login/', views.custom_login, name='login'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('secure/<uidb64>/<token>', views.secure, name='secure'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path('create_staff/', views.create_access_level_5_user, name='create_staff'),
    path("staff_no/", views.staff_no, name="staff_no"),
    path("permission_denied/", views.not_allowed, name="denials"),
    path("f_pass", views.f_pass, name="f_pass"),
    path('del_user/<int:user_id>', views.delete_user, name='del_user'),
    path('terms_acceptance/',
         views.terms_acceptance, name='terms_acceptance'),
    path('vacancy/<int:vacancy_id>/terms_acceptance/',
         views.internal_terms_acceptance, name='internal_terms_acceptance'),
    path('internship/<int:vacancy_id>/terms_acceptance/',
         views.internship_terms_acceptance, name='internship_terms_acceptance'),
    path('attachment/<int:vacancy_id>/terms_acceptance/',
         views.attachment_terms_acceptance, name='attachment_terms_acceptance'),
]

vacancies/urls.py
from django.urls import path
from . import views

app_name = 'vacancies'
urlpatterns = [
    path('job/<int:vacancy_id>/', views.job, name='job'),
    path("internships", views.internships, name="internships"),
    path('internship/<int:vacancy_id>/', views.internship, name='internship'),
    path("attachments", views.attachments, name="attachments"),
    path('attachment/<int:vacancy_id>/', views.attachment, name='attachment'),
    path('apply/<int:vacancy_id>/', views.apply, name='apply'),
    path('applications/', views.applications, name='applications'),
    path('reapply/<int:application_id>/',
         views.reapply_application, name='recall_application'),
    path('delete/<int:application_id>/',
         views.delete_application, name='delete_application'),
    path("internal", views.internal, name="internal"),
    path('internal_detail/<int:vacancy_id>/',
         views.internal_detail, name='internal_detail'),
    path('application/success/', views.application_succ, name='apply_succ'),
    path('vacancies/apply_fail', views.apply_fail, name='apply_fail'),

]

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from users.models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from vacancies.models import *
from datetime import *
from users.decorators import *
from django.db.models import Q
from users.checks import *
from .experience import *
from users.forms import *
import datetime


@access_level_check(user_access_level=5, redirect_view_name='vacancies:internal')
def index(request):
    job_types = JobType.objects.exclude(name="Internal")
    print(job_types)

    return render(request, 'main/index.html', {'job_types': job_types})


def job_type_detail(request, pk):

    search_query = request.GET.get('search')
    job_type_filter = request.GET.get('vacancy_type')
    current_date = date.today()

    job_type = get_object_or_404(JobType, pk=pk)

    if job_type.name == 'Internal':
        return redirect(request.META.get('HTTP_REFERER', '/'))

    jobs = Vacancy.objects.filter(
        job_type=job_type,
        date_close__gte=current_date
    ).exclude(job_type__name='Internal')

    job_disciplines = JobDiscipline.objects.all()

    if search_query:
        jobs = jobs.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query)
        )

    if job_type_filter:
        jobs = jobs.filter(job_discipline__name=job_type_filter)

    context = {
        'job_type': job_type,
        'jobs': jobs,
        'job_disciplines': job_disciplines,
        'search_query': search_query,
        'selected_job_type': job_type_filter,
    }

    return render(request, 'main/job_type_detail.html', context)


def job_detail(request, job_id):
    job = get_object_or_404(Vacancy, pk=job_id)
    job_type = job.job_type.name
    user = request.user

    # Check if the job type is "Internal"
    if job_type == "Internal":
        if not user.is_authenticated:
            messages.error(request, "Unauthorized Access")
            return redirect(request.META.get('HTTP_REFERER', '/'))
        if user.access_level != 5:
            messages.error(
                request, "Unauthorised Access")
            return redirect(request.META.get('HTTP_REFERER', '/'))
    else:
        if user.is_authenticated and user.access_level == 5:
            messages.error(
                request, "You do not have permission to view this job.")
            return redirect(request.META.get('HTTP_REFERER', '/'))

    user_accepted_terms = None
    if user.is_authenticated:
        user_accepted_terms, created = UserAcceptedTerms.objects.get_or_create(
            user=user)

    context = {
        'job': job,
        'terms': user_accepted_terms
    }

    return render(request, 'main/job_detail.html', context)


@login_required
def bio_info(request):
    job_types = JobType.objects.exclude(name="Internal")
    user = request.user

    if user.access_level == 5:
        try:
            profile_update = ProfileUpdate.objects.get(user=user)
            if not profile_update.password_changed:
                return render(request, 'main/password_change_required.html')
        except ProfileUpdate.DoesNotExist:
            return render(request, 'main/password_change_required.html')
        return redirect('main:staff_profile')

    try:
        resume = Resume.objects.get(user=user)
    except Resume.DoesNotExist:

        full_name = f"{user.first_name} {user.last_name}"
        id_number = user.id_number
        email_address = user.email
        resume = Resume.objects.create(
            user=user,
            full_name=full_name,
            id_number=id_number,
            email_address=email_address
        )

    basic_education_instance = BasicEducation.objects.filter(user=user).first()
    highest_edu_level = FurtherStudies.objects.filter(
        user=user).order_by('-certifications__index').first()

    if highest_edu_level is not None and highest_edu_level.certifications is not None:
        highest_edu_level = highest_edu_level.certifications.name
    else:
        highest_edu_level = None

    fields_provided = resume_fields_provided(request)

    return render(request, 'main/bio_info.html', {
        'user': user,
        'resume': resume,
        'be': basic_education_instance,
        'all_fields': fields_provided,
        'highest_edu_level': highest_edu_level,

    })


@login_required
def high_school(request):
    user = request.user

    basic_education_instances = BasicEducation.objects.filter(user=user)[:2]
    further_studies_instance = FurtherStudies.objects.filter(user=user).first()
    all_fields_provided = basic_academic_fields_provided(request)

    return render(request, 'main/high_school.html', {
        'user': user,
        'be': basic_education_instances,
        'fs': further_studies_instance,
        'all_fields': all_fields_provided
    })


@login_required
def college(request):
    user = request.user

    further_studies_instance = FurtherStudies.objects.filter(user=user).all()
    certs_instance = Certification.objects.filter(user=user).all()
    all_fields_provided = higher_education_fields_provided(request)

    return render(request, 'main/college.html', {
        'user': user,
        'fs': further_studies_instance,
        'certs': certs_instance,
        'all_fields': all_fields_provided

    })


@login_required
def certs(request):
    user = request.user

    certification_instance = Certification.objects.filter(user=user).all()
    further_studies_instance = FurtherStudies.objects.filter(user=user).all()
    membership_instance = Membership.objects.filter(user=user).all()
    certs_fields_provided = certification_fields_provided(request)
    print(certs_fields_provided)

    return render(request, 'main/certs.html', {
        'user': user,
        'fs': further_studies_instance,
        'ms': membership_instance,
        'certs': certification_instance,
        'all_fields': certs_fields_provided

    })


@login_required
def memberships(request):
    user = request.user

    membership_instance = Membership.objects.filter(user=user).all()
    certification_instance = Certification.objects.filter(user=user).all()
    wx_instance = WorkExperience.objects.filter(user=user).all()
    memberships_fields_provided = membership_fields_provided(request)
    print(memberships_fields_provided)

    return render(request, 'main/memberships.html', {
        'user': user,
        'ms': membership_instance,
        'certs': certification_instance,
        'wx': wx_instance,
        'all_fields': memberships_fields_provided


    })


@login_required
def refs(request):
    user = request.user

    work_experience_instance = WorkExperience.objects.filter(user=user).all()
    certification_instance = Certification.objects.filter(user=user).all()
    referee_instance = Referee.objects.filter(user=user).all()
    refs_fields_provided = referee_fields_provided(request)

    return render(request, 'main/refs.html', {
        'user': user,
        'wx': work_experience_instance,
        'refs': referee_instance,
        'all_fields': refs_fields_provided

    })


@login_required
def experience(request):
    user = request.user

    wx_instance = WorkExperience.objects.filter(user=user).all()
    certification_instance = Certification.objects.filter(user=user).all()
    referee_instance = Referee.objects.filter(user=user).all()
    experiences_fields_provided = experience_fields_provided(request)

    return render(request, 'main/experience.html', {
        'user': user,
        'wx': wx_instance,
        'certs': certification_instance,
        'refs': referee_instance,
        'all_fields': experiences_fields_provided

    })


@login_required
def resume(request):
    user = request.user

    # Generate full_name safely
    full_name = " ".join(
        filter(None, [user.first_name, user.last_name])) or "No Name Provided"
    id_number = user.id_number or "No ID Provided"

    # Ensure resume exists or create one
    resume, created = Resume.objects.get_or_create(
        user=user,
        defaults={
            'full_name': full_name,
            'id_number': id_number,
            'email_address': user.email
        }
    )

    basic_academic = BasicEducation.objects.filter(user=user)
    higher_education = FurtherStudies.objects.filter(
        user=user).order_by('-date_ended')
    wx_instance = WorkExperience.objects.filter(
        user=user).order_by('-date_ended')
    certification_instance = Certification.objects.filter(
        user=user).order_by('-date_attained')
    membership_instance = Membership.objects.filter(
        user=user).order_by('-date_joined')
    referee_instance = Referee.objects.filter(user=user)
    executive_summery = ProfessionalSummary.objects.filter(user=user)

    all_instances_provided = all_fields_provided(request)

    context = {
        'be': basic_academic,
        'he': higher_education,
        'resume': resume,
        'user': user,
        'wx': wx_instance,
        'certs': certification_instance,
        'ms': membership_instance,
        'refs': referee_instance,
        'summary': executive_summery,
        'all_fields': all_instances_provided,
    }

    return render(request, 'main/resume.html', context)


@login_required
def staff(request):
    user = request.user
    resume = None
    further_studies = None
    memberships = None
    work_experiences = None
    certifications = None

    if user.access_level == 5:
        try:
            profile_update = ProfileUpdate.objects.get(user=user)
            if not profile_update.password_changed:
                return render(request, 'main/pass_change.html')
        except ProfileUpdate.DoesNotExist:
            # If no ProfileUpdate record exists, consider it as not changed.
            pass

        # Check if the user has a resume
        try:
            resume = Resume.objects.get(user=user)
        except Resume.DoesNotExist:

main/templates/main/includes/footer.html
<div style="background-color: #7266bb; color: #fff; padding: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="text-center text-md-center">
                    <h4 class="text-white">Location</h4>
                    <p>KenGen Pension Plaza II, Kolobot Road, Parklands</p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="text-center text-md-center">
                    <h4 class="text-white">Address</h4>
                    <p>P.o. Box 47936, 00100 Nairobi</p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="text-center text-md-center">
                    <h4 class="text-white">Contacts</h4>
                    <p>+254 203666000<br>+254 711036000 / +254 732116000</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="background-color: #fd7e14; color: #fff; padding: 10px; text-align: center;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <p>&copy; <span id="current-year"></span> KenGen Careers Portal. All rights reserved.</p>
            </div>
        </div>
    </div>
</div>

main/templates/main/includes/messaging.html
<div class="container" id="alert-container">

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

</div>

main/templates/main/includes/navbar.html
{% load static %}
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="/">
                <img src="{% static 'dashboard/images/icon.png' %}" alt="Logo" class="d-inline-block align-top" style="max-height: 60px;">
                <span class="navbar-text mx-auto" style="font-size: 1.4rem;">Careers Portal</span>
            </a>
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated and user.access_level == 5 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'vacancies:internal' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:staff_profile' %}">Resume</a>
                    </li>
                    {% endif %}
                       
                    {% if user.is_authenticated %}
                    {% if user.access_level != 5 %}
                        <li class="nav-item">
                            <a class="nav-link" href="/">
                                Home
                            </a>
                        </li>
                    {% endif %}
                   {% endif %}
                    
                   {% if user.is_authenticated %}
                   {% if user.access_level != 5 %}
                       <li class="nav-item">
                           <a class="nav-link" href="{% url 'main:bio_info' %}">
                               Resume
                           </a>
                       </li>
                   {% endif %}
               {% endif %}
               {% if user.is_authenticated %}
               {% if user.access_level != 5 %}
                   <li class="nav-item">
                       <a class="nav-link" href="https://www.kengen.co.ke/index.php/our-company/who-we-are.html" target="_blank">
                           Why Kengen
                       </a>
                   </li>
               {% endif %}
           {% endif %}

               {% if user.is_authenticated %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'main:terms' %}">
                       T&Cs
                   </a>
               </li>
               {%  endif %}

             <li class="nav-item">
               <a class="nav-link" href="{% url 'main:how' %}">
               How to apply
               </a>
           </li>

           <li class="nav-item">
               <a class="nav-link" href="https://www.kengen.co.ke/index.php/information-center/faqs.html" target="_blank">
                   FAQS
               </a>
           </li>
           
           {% if user.is_authenticated %}
           <li class="nav-item">
               <a class="nav-link" href="{% url 'vacancies:applications' %}">
               My Applications
               </a>
           </li>
           {% endif %}
                   {% if user.is_authenticated %}
                   <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user me-2"></i> 
                        {{ user.username }}
                       
                    </a>  
                                      
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item active" href="#">
                                <div>
                                    {% if user.is_superuser %}
                                        
                                    <i class="fas fa-user me-2"></i>     Superuser
                                        
                                    {% else %}
                                       
                                    <i class="fas fa-user me-2"></i> User
                                     
                                    {% endif %}
                                </div>
                            </a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'users:profile'  user.id %}">Profile</a></li>
                       
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                    </ul>
                </li>
                  
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Sign-in/Register</a>
                </li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>